// <auto-generated />
namespace Numero3.EntityFramework.Demo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_product : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_product));
        
        string IMigrationMetadata.Id
        {
            get { return "201901162227076_add_product"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
